# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cuenta', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo_cuenta', models.CharField(max_length=7, unique=True)),
                ('cuenta_padre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='datosResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100)),
                ('codCuenta', models.CharField(max_length=10)),
                ('saldo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='detalleKardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCuenta', models.CharField(max_length=10)),
                ('concepto', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
            ],
            options={
                'verbose_name': 'Docuemnto',
                'verbose_name_plural': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='EmpPlanilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salPersonal', models.FloatField(blank=True, null=True)),
                ('nomEmpleado', models.CharField(max_length=70)),
                ('anios', models.FloatField()),
                ('isss', models.FloatField(blank=True, null=True)),
                ('afp', models.FloatField(blank=True, null=True)),
                ('insaforp', models.FloatField(blank=True, null=True)),
                ('vaca', models.FloatField(blank=True, null=True)),
                ('aguinaldo', models.FloatField(blank=True, null=True)),
                ('cmo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_grupo', models.CharField(max_length=50, unique=True)),
                ('codigo_gcuenta', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantEntrada', models.IntegerField()),
                ('cantSalida', models.IntegerField()),
                ('cantExistencia', models.IntegerField()),
                ('precEntrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precSalida', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precExistencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montoEntrada', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montoSalida', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montoExistencia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('detall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.detalleKardex')),
            ],
        ),
        migrations.CreateModel(
            name='LibroMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100)),
                ('codCuenta', models.CharField(max_length=10)),
                ('saldoDeudor', models.FloatField()),
                ('saldoAcreedor', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('saldo', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'LibroMayor',
                'verbose_name_plural': 'LibroMayor',
            },
        ),
        migrations.CreateModel(
            name='OrdenFab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCuenta', models.CharField(max_length=100, unique=True)),
                ('saldo', models.FloatField(default=0.0)),
                ('materiaPrima', models.FloatField(default=0)),
                ('manoObra', models.FloatField(default=0)),
                ('cif', models.FloatField(default=0)),
                ('invInici', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('usr_aperturo', models.CharField(max_length=20)),
                ('usr_cerro', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=70)),
                ('salNominal', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Puestos',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='sancionSalarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=10)),
                ('unidades', models.IntegerField()),
                ('monto', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.EmpPlanilla')),
            ],
            options={
                'verbose_name': 'Sanciones',
                'verbose_name_plural': 'Sanciones',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo', models.CharField(max_length=50)),
                ('codigo_tcuenta', models.CharField(max_length=1)),
                ('disminuye_en', models.CharField(max_length=10)),
                ('aumenta_en', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='libromayor',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.PeriodoContable'),
        ),
        migrations.AddField(
            model_name='grupocuenta',
            name='tipo_cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contable.TipoCuenta'),
        ),
        migrations.AddField(
            model_name='estadoresultado',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contable.PeriodoContable'),
        ),
        migrations.AddField(
            model_name='empplanilla',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.Puesto'),
        ),
        migrations.AddField(
            model_name='diario',
            name='mayor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.LibroMayor'),
        ),
        migrations.AddField(
            model_name='datosresultado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.EstadoResultado'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contable.GrupoCuenta'),
        ),
    ]
