# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfab',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
