# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCuenta', models.CharField(max_length=100, unique=True)),
                ('saldo', models.FloatField(default=0.0)),
                ('materiaPrima', models.FloatField(default=0)),
                ('manoObra', models.FloatField(default=0)),
                ('cif', models.FloatField(default=0)),
                ('invInici', models.FloatField(default=0)),
            ],
        ),
    ]
